palex_blog_homepage:
    path:     /
    defaults: { _controller: PalexBlogBundle:Blog:index }

palex_blog_category_post:
    path:     /categories/{slug}
    defaults: { _controller: PalexBlogBundle:Blog:showByCategory }


palex_blog_post_add:
    path:     /addpost/
    defaults: { _controller: PalexBlogBundle:Blog:addPost }

palex_blog_post:
    path:     /{category}/{slug}
    defaults: { _controller: PalexBlogBundle:Blog:post }

palex_blog_admin:
    path:     /admin/
    defaults: { _controller: PalexBlogBundle:Admin:index }
