services:
  palex_blog.twig.cut_extension:
        class: Palex\BlogBundle\Twig\CutExtension
        public: false
        tags:
            - { name: twig.extension }

  palex_blog.menu.menu_builder:
        class: Palex\BlogBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
