<?php

namespace Palex\BlogBundle\Repository;

/**
 * FinderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinderRepository extends \Doctrine\ORM\EntityRepository
{
}
